### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by FlyDogDaDa** [rhasspy/pysilero-vad#2]
I've updated pip to the latest version but that didn't fix this installation error.
```
(.venv) D:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Scripts>python -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in d:\documents\desktop\githubs\autovideoediting\.venv\lib\site-packages (69.5.1)

(.venv) D:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Scripts>pip install pysilero-vad
Collecting pysilero-vad
  Using cached pysilero_vad-1.0.0-py3-none-any.whl.metadata (1.2 kB)
Collecting onnxruntime<2,>=1.10.0 (from pysilero-vad)
  Using cached onnxruntime-1.17.3-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
Collecting numpy<1.26 (from pysilero-vad)
  Using cached numpy-1.25.2.tar.gz (10.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "d:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "d:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "d:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "d:\Documents\Desktop\GitHubs\AutoVideoEditing\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Home\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "D:\TEMP\pip-build-env-jmuh_7ym\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "D:\TEMP\pip-build-env-jmuh_7ym\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "D:\TEMP\pip-build-env-jmuh_7ym\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by synesthesiam** [comment]
This seems to be a misconfiguration related to your Python setup: https://github.com/copier-org/copier/issues/1603
